const PARSE_ERROR = -32700;
const INVALID_REQUEST = -32600;
const METHOD_NOT_FOUND = -32601;
const INVALID_PARAMS = -32602;
const SERVER_ERROR = -32000;
const SERVER_ERROR_MAX = -32099;

exports.PARSE_ERROR = PARSE_ERROR;
exports.INVALID_REQUEST = INVALID_REQUEST;
exports.METHOD_NOT_FOUND = METHOD_NOT_FOUND;
exports.INVALID_PARAMS = INVALID_PARAMS;
exports.SERVER_ERROR = SERVER_ERROR;
exports.SERVER_ERROR_MAX = SERVER_ERROR_MAX;
